/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PsRouteImport } from './routes/ps'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ImagemRouteImport } from './routes/imagem'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PremiumIndexRouteImport } from './routes/premium.index'
import { Route as PremiumSucessoRouteImport } from './routes/premium.sucesso'
import { Route as JogarModeRouteImport } from './routes/jogar.$mode'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'

const PsRoute = PsRouteImport.update({
  id: '/ps',
  path: '/ps',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagemRoute = ImagemRouteImport.update({
  id: '/imagem',
  path: '/imagem',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumIndexRoute = PremiumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PremiumRoute,
} as any)
const PremiumSucessoRoute = PremiumSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => PremiumRoute,
} as any)
const JogarModeRoute = JogarModeRouteImport.update({
  id: '/jogar/$mode',
  path: '/jogar/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/como-jogar': typeof ComoJogarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/imagem': typeof ImagemRoute
  '/premium': typeof PremiumRouteWithChildren
  '/ps': typeof PsRoute
  '/jogar/$mode': typeof JogarModeRoute
  '/premium/sucesso': typeof PremiumSucessoRoute
  '/premium/': typeof PremiumIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/como-jogar': typeof ComoJogarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/imagem': typeof ImagemRoute
  '/ps': typeof PsRoute
  '/jogar/$mode': typeof JogarModeRoute
  '/premium/sucesso': typeof PremiumSucessoRoute
  '/premium': typeof PremiumIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arquivo': typeof ArquivoRoute
  '/como-jogar': typeof ComoJogarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/imagem': typeof ImagemRoute
  '/premium': typeof PremiumRouteWithChildren
  '/ps': typeof PsRoute
  '/jogar/$mode': typeof JogarModeRoute
  '/premium/sucesso': typeof PremiumSucessoRoute
  '/premium/': typeof PremiumIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/como-jogar'
    | '/estatisticas'
    | '/imagem'
    | '/premium'
    | '/ps'
    | '/jogar/$mode'
    | '/premium/sucesso'
    | '/premium/'
    | '/api/public/mp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arquivo'
    | '/como-jogar'
    | '/estatisticas'
    | '/imagem'
    | '/ps'
    | '/jogar/$mode'
    | '/premium/sucesso'
    | '/premium'
    | '/api/public/mp-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arquivo'
    | '/como-jogar'
    | '/estatisticas'
    | '/imagem'
    | '/premium'
    | '/ps'
    | '/jogar/$mode'
    | '/premium/sucesso'
    | '/premium/'
    | '/api/public/mp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArquivoRoute: typeof ArquivoRoute
  ComoJogarRoute: typeof ComoJogarRoute
  EstatisticasRoute: typeof EstatisticasRoute
  ImagemRoute: typeof ImagemRoute
  PremiumRoute: typeof PremiumRouteWithChildren
  PsRoute: typeof PsRoute
  JogarModeRoute: typeof JogarModeRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ps': {
      id: '/ps'
      path: '/ps'
      fullPath: '/ps'
      preLoaderRoute: typeof PsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imagem': {
      id: '/imagem'
      path: '/imagem'
      fullPath: '/imagem'
      preLoaderRoute: typeof ImagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/': {
      id: '/premium/'
      path: '/'
      fullPath: '/premium/'
      preLoaderRoute: typeof PremiumIndexRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/premium/sucesso': {
      id: '/premium/sucesso'
      path: '/sucesso'
      fullPath: '/premium/sucesso'
      preLoaderRoute: typeof PremiumSucessoRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/jogar/$mode': {
      id: '/jogar/$mode'
      path: '/jogar/$mode'
      fullPath: '/jogar/$mode'
      preLoaderRoute: typeof JogarModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PremiumRouteChildren {
  PremiumSucessoRoute: typeof PremiumSucessoRoute
  PremiumIndexRoute: typeof PremiumIndexRoute
}

const PremiumRouteChildren: PremiumRouteChildren = {
  PremiumSucessoRoute: PremiumSucessoRoute,
  PremiumIndexRoute: PremiumIndexRoute,
}

const PremiumRouteWithChildren =
  PremiumRoute._addFileChildren(PremiumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArquivoRoute: ArquivoRoute,
  ComoJogarRoute: ComoJogarRoute,
  EstatisticasRoute: EstatisticasRoute,
  ImagemRoute: ImagemRoute,
  PremiumRoute: PremiumRouteWithChildren,
  PsRoute: PsRoute,
  JogarModeRoute: JogarModeRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
